CREATE TABLE [dbo].[TransactionsShipment] (
    [tr_transactionID]          BIGINT        NOT NULL,
    [tr_ship_notShipped]        BIT           DEFAULT ((0)) NULL,
    [tr_ship_notShipped_reason] VARCHAR (500) NULL,
    [tr_ship_extension]         VARCHAR (100) NULL,
    [tr_ship_appReceived]       BIT           DEFAULT ((0)) NULL,
    [tr_expectedShipment]       DATETIME      NULL,
    [tr_inTransit]              DATETIME      NULL,
    [tr_shipped]                BIT           DEFAULT ((0)) NULL,
    [tr_dateShipped]            DATETIME      NULL,
    [tr_expectedArrival]        DATETIME      NULL,
    [tr_transitPort]            VARCHAR (500) NULL,
    [tr_ship_arrivedAtPort]     BIT           DEFAULT ((0)) NULL,
    [tr_dateArrived]            DATETIME      NULL,
    [tr_actualArrived]          DATETIME      NULL,
    [tr_ship_BlNo]              VARCHAR (50)  NULL,
    [tr_ship_invoiceNo]         VARCHAR (50)  NULL,
    [tr_ship_invoiceAmt]        INT           NULL,
    [tr_ship_quantity]          INT           NULL,
    [tr_ship_vesselNo]          VARCHAR (50)  NULL,
    [tr_ship_primaryShipperId]  BIGINT        NULL,
    [tr_ship_portLoad]          VARCHAR (500) NULL,
    [tr_ship_portDest]          VARCHAR (500) NULL,
    [tr_ship_shipLineCont]      VARCHAR (500) NULL,
    [tr_createdBy]              INT           NOT NULL,
    [tr_createdOn]              DATETIME      NULL,
    [tr_editedBy]               INT           NULL,
    [tr_editedOn]               DATETIME      NULL,
    [tr_ship_chk_reason]        BIT           DEFAULT ((0)) NULL,
    [tr_ship_chk_shpExt]        BIT           DEFAULT ((0)) NULL,
    [tr_ship_chk_expShp]        BIT           DEFAULT ((0)) NULL,
    [tr_ship_chk_inTransit]     BIT           DEFAULT ((0)) NULL,
    [tr_ship_chk_dateShipped]   BIT           DEFAULT ((0)) NULL,
    [tr_ship_chk_expArrival]    BIT           DEFAULT ((0)) NULL,
    [tr_ship_chk_transitPort]   BIT           DEFAULT ((0)) NULL,
    [tr_ship_chk_dateArrived]   BIT           DEFAULT ((0)) NULL,
    [tr_ship_chk_actualArrived] BIT           DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([tr_transactionID] ASC),
    FOREIGN KEY ([tr_createdBy]) REFERENCES [dbo].[AppUsers] ([UserID]),
    FOREIGN KEY ([tr_editedBy]) REFERENCES [dbo].[AppUsers] ([UserID]),
    FOREIGN KEY ([tr_ship_primaryShipperId]) REFERENCES [dbo].[BusinessPartner] ([bp_ID]),
    FOREIGN KEY ([tr_transactionID]) REFERENCES [dbo].[Transactions] ([tr_transactionID])
);

