//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de_server.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessPartner_Contacts
    {
        public long bp_cont_ID { get; set; }
        public long bp_ID { get; set; }
        public Nullable<bool> bp_Cont_IsPrimary { get; set; }
        public string bp_Cont_fullName { get; set; }
        public string bp_Cont_designation { get; set; }
        public string bp_Cont_Email { get; set; }
        public string bp_Cont_PrimaryNumber { get; set; }
        public string bp_Cont_SecondryNumber { get; set; }
        public System.DateTime bp_Cont_CreatedOn { get; set; }
        public Nullable<System.DateTime> bp_Cont_LastEditedOn { get; set; }
        public Nullable<int> bp_Cont_CreatedBy { get; set; }
        public Nullable<int> bp_Cont_EditedBy { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual BusinessPartner BusinessPartner { get; set; }
    }
}
