//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de_server.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessPartner_BankDetails
    {
        public long bankDetails_ID { get; set; }
        public long bp_ID { get; set; }
        public string branchAddress { get; set; }
        public string bankName { get; set; }
        public string AccountTitle { get; set; }
        public string AccountNumber { get; set; }
        public string AccountCountry { get; set; }
    
        public virtual BusinessPartner BusinessPartner { get; set; }
    }
}
