//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de_server.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class dailyProductPrice
    {
        public int Prod_ID { get; set; }
        public System.DateTime PriceDate { get; set; }
        public Nullable<int> Price { get; set; }
        public int tr_createdBy { get; set; }
        public Nullable<int> tr_editedBy { get; set; }
        public System.DateTime tr_createdOn { get; set; }
        public Nullable<System.DateTime> tr_editedOn { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual Product Product { get; set; }
    }
}
