//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de_server.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsCommission
    {
        public long tr_transactionID { get; set; }
        public Nullable<bool> tr_brokerInvolved { get; set; }
        public Nullable<bool> tr_sellerBroker { get; set; }
        public Nullable<long> tr_sellerBrokerID { get; set; }
        public string tr_sellerBroker_comm_type { get; set; }
        public Nullable<int> tr_sellerBroker_comm { get; set; }
        public Nullable<bool> tr_buyerBroker { get; set; }
        public Nullable<long> tr_buyerBrokerID { get; set; }
        public string tr_buyerBroker_comm_type { get; set; }
        public Nullable<int> tr_buyerBroker_comm { get; set; }
        public Nullable<int> tr_own_Commission { get; set; }
        public string tr_ownCommissionType { get; set; }
        public Nullable<int> tr_difference { get; set; }
        public Nullable<int> tr_discount { get; set; }
        public Nullable<int> tr_netCommission { get; set; }
        public int tr_createdBy { get; set; }
        public Nullable<System.DateTime> tr_createdOn { get; set; }
        public Nullable<int> tr_editedBy { get; set; }
        public Nullable<System.DateTime> tr_editedOn { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual BusinessPartner BusinessPartner { get; set; }
        public virtual BusinessPartner BusinessPartner1 { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
