//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de_server.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.TransactionFiles = new HashSet<TransactionFile>();
            this.TransactionFiles1 = new HashSet<TransactionFile>();
            this.TransactionsNotes = new HashSet<TransactionsNote>();
            this.TransactionsSecondaries = new HashSet<TransactionsSecondary>();
        }
    
        public long tr_transactionID { get; set; }
        public Nullable<System.DateTime> tr_date { get; set; }
        public Nullable<long> tr_bpBuyerID { get; set; }
        public Nullable<long> tr_bpSellerID { get; set; }
        public Nullable<int> tr_productID { get; set; }
        public string tr_origin { get; set; }
        public Nullable<decimal> tr_quantity { get; set; }
        public Nullable<decimal> tr_price { get; set; }
        public string tr_packing { get; set; }
        public Nullable<System.DateTime> tr_shipment_start { get; set; }
        public Nullable<System.DateTime> tr_shipment_end { get; set; }
        public string tr_fileID { get; set; }
        public string tr_contractID { get; set; }
        public string tr_other_info { get; set; }
        public int tr_createdBy { get; set; }
        public Nullable<System.DateTime> tr_createdOn { get; set; }
        public Nullable<int> tr_editedBy { get; set; }
        public Nullable<System.DateTime> tr_editedOn { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual BusinessPartner BusinessPartner { get; set; }
        public virtual BusinessPartner BusinessPartner1 { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<TransactionFile> TransactionFiles { get; set; }
        public virtual ICollection<TransactionFile> TransactionFiles1 { get; set; }
        public virtual TransactionsCommission TransactionsCommission { get; set; }
        public virtual TransactionsContract TransactionsContract { get; set; }
        public virtual ICollection<TransactionsNote> TransactionsNotes { get; set; }
        public virtual ICollection<TransactionsSecondary> TransactionsSecondaries { get; set; }
        public virtual TransactionsShipment TransactionsShipment { get; set; }
        public virtual TransactionsStatu TransactionsStatu { get; set; }
    }
}
