//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de_server.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEvent
    {
        public int EventID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
        public string EventDescription { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
